<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_s-image</name>
   <tag></tag>
   <elementGuidId>5c2c656d-3cd7-465d-9430-536b34e6ceca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/div/div/div/span/div/div[5]/div/div/div/div/span/div/div/div/div/div/div[2]/div/span/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>66fabab0-cee3-4a04-98ca-673a4a547e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-image</value>
      <webElementGuid>4e58376d-215b-4163-8f9d-2c2c6882d8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/71G7wMeIZ8L._AC_UY218_.jpg</value>
      <webElementGuid>ce27ca4f-f137-409c-95fa-b96acd077287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/71G7wMeIZ8L._AC_UY218_.jpg 1x, https://m.media-amazon.com/images/I/71G7wMeIZ8L._AC_UY327_FMwebp_QL65_.jpg 1.5x, https://m.media-amazon.com/images/I/71G7wMeIZ8L._AC_UY436_FMwebp_QL65_.jpg 2x, https://m.media-amazon.com/images/I/71G7wMeIZ8L._AC_UY545_FMwebp_QL65_.jpg 2.5x, https://m.media-amazon.com/images/I/71G7wMeIZ8L._AC_UY654_FMwebp_QL65_.jpg 3x</value>
      <webElementGuid>5dee111e-338f-45e6-a38c-e50071dff6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sponsored Ad - Samsung Galaxy S24 Plus 5G (Cobalt Violet, 12GB, 512GB Storage)</value>
      <webElementGuid>e9380a59-4712-4e61-a7f1-4c93afee5a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>17050ba8-0b2c-4b9a-9720-bd226520b216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-latency</name>
      <type>Main</type>
      <value>s-product-image</value>
      <webElementGuid>6ada3837-8453-464c-a103-026d99cd318a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-source-density</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0ed6429c-055c-41b2-bb20-c31c4bdec0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[@class=&quot;s-desktop-width-max s-desktop-content s-opposite-dir s-wide-grid-style sg-row&quot;]/div[@class=&quot;sg-col-20-of-24 s-matching-dir sg-col-16-of-20 sg-col sg-col-8-of-12 sg-col-12-of-16&quot;]/div[@class=&quot;sg-col-inner&quot;]/span[@class=&quot;rush-component s-latency-cf-section&quot;]/div[@class=&quot;s-main-slot s-result-list s-search-results sg-row&quot;]/div[@class=&quot;sg-col-20-of-24 s-result-item s-asin sg-col-0-of-12 sg-col-16-of-20 AdHolder sg-col s-widget-spacing-small sg-col-12-of-16&quot;]/div[@class=&quot;sg-col-inner&quot;]/div[@class=&quot;s-widget-container s-spacing-small s-widget-container-height-small celwidget slot=MAIN template=SEARCH_RESULTS widgetId=search-results_2&quot;]/div[@class=&quot;rush-component&quot;]/div[@class=&quot;rush-component s-featured-result-item&quot;]/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;puis-card-container s-card-container s-overflow-hidden aok-relative puis-include-content-margin puis puis-v1x9xtdrqwkf2b2sy3gv3bhvhpn s-latency-cf-section puis-card-border&quot;]/div[@class=&quot;a-section&quot;]/div[@class=&quot;puisg-row&quot;]/div[@class=&quot;puisg-col puisg-col-4-of-12 puisg-col-4-of-16 puisg-col-4-of-20 puisg-col-4-of-24 puis-list-col-left&quot;]/div[@class=&quot;puisg-col-inner&quot;]/div[@class=&quot;s-product-image-container aok-relative s-text-center s-image-overlay-grey puis-image-overlay-grey s-padding-left-small s-padding-right-small puis-flex-expand-height puis puis-v1x9xtdrqwkf2b2sy3gv3bhvhpn&quot;]/div[@class=&quot;aok-relative&quot;]/span[@class=&quot;rush-component&quot;]/a[@class=&quot;a-link-normal s-no-outline&quot;]/div[@class=&quot;a-section aok-relative s-image-fixed-height&quot;]/img[@class=&quot;s-image&quot;]</value>
      <webElementGuid>8e091d69-5360-4a42-b891-7f2dc8a4f6d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/span/div/div[5]/div/div/div/div/span/div/div/div/div/div/div[2]/div/span/a/div/img</value>
      <webElementGuid>eb39e7e7-8c50-4598-974a-31858b210161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sponsored Ad - Samsung Galaxy S24 Plus 5G (Cobalt Violet, 12GB, 512GB Storage)']</value>
      <webElementGuid>c9590591-6503-4f4d-856c-e54811d17d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/span/div/div/div/div/div/div[2]/div/span/a/div/img</value>
      <webElementGuid>af4b72b9-b958-4e3d-a82c-beb4ccf81af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://m.media-amazon.com/images/I/71G7wMeIZ8L._AC_UY218_.jpg' and @alt = 'Sponsored Ad - Samsung Galaxy S24 Plus 5G (Cobalt Violet, 12GB, 512GB Storage)']</value>
      <webElementGuid>d007e080-cd40-4ea2-9003-b68695fd2690</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
