<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_All</name>
   <tag></tag>
   <elementGuidId>ba679336-e29d-431e-b08f-178813939a1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='all-tab-desktop']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.a-size-small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>072540c2-9550-493d-9077-2b19bd13615e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-small</value>
      <webElementGuid>92b115db-c69d-450e-9d68-d550987fdd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            All
                        </value>
      <webElementGuid>00ea97d5-82a8-4c75-9277-668602f85640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;all-tab-desktop&quot;)/span[@class=&quot;a-declarative&quot;]/span[@class=&quot;a-size-small&quot;]</value>
      <webElementGuid>5bca74c0-51df-4c80-875d-4f4d8e2641fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='all-tab-desktop']/span/span</value>
      <webElementGuid>b56361d8-2f9c-4b83-bcc3-06310ac85c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span/span</value>
      <webElementGuid>c2b2dce3-325b-46e3-afc8-dfffc9563f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                            All
                        ' or . = '
                            All
                        ')]</value>
      <webElementGuid>b059bc67-7d3a-4e56-9ad6-f0ab6f928879</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
